### ISSUE TITLE
Little snag

### ISSUE THREAD

**Issue by zOOge** [kodywilson/metrics#2]
Hi there, when running the scripts, I am hitting a wall.
Trying with 2 xtremio:s according to instructions and get this:
[root@monitor]# ruby /root/git/metrics/storage/perf_tracer_xtremio.rb
/root/git/metrics/storage/perf_tracer_xtremio.rb:38:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /root/git/metrics/storage/perf_tracer_xtremio.rb:29:in `each'
	from /root/git/metrics/storage/perf_tracer_xtremio.rb:29:in `<main>'
[root@monitor]#
xtremio_stats.json:
    {
      "base_dir": "/statistics/folder/",
      "database": "metrics",
      "db_host": "localhost",
      "db_user": "metricman",
      "db_pass": "base64_encoded_password",
      "headers": {
        "Content-Type": "application/json",
        "Accept": "application/json"
      },
      "arrays": {
        "xtremio1": "Basic base64_encoded user:password",
        "xtremio1": "Basic base64_encoded user:password"
      }
    }

I have also changed this line:
base_url = 'https://' + key + '.nordstrom.net/api/json/v2/types/'
into:
base_url = 'https://' + key + '.ourdomain.com/api/json/v2/types/'

Can you help med go further ?

**Comment by kodywilson** [comment]
Hi zOOge,

I may be able to help you get to the bottom of it. My guess is that something is not getting read correctly from your json file. What I always do in situations like this is use the pry gem and/or puts statements to get better information.

Normally the error message you are getting means that Ruby expected an array and was instructed to iterate over each item in it, but the array does not exist. This can happen if you have a string instead of an array in your variable.

If I was you, I would start off by inserting these lines above line 29: conf['arrays'].each do |key, val|
puts conf['arrays']
puts conf['arrays'].class
exit

This will puts whatever is in conf['arrays'], show if it is an array, and then exit skipping the failing part of the code.

Try that and see if it helps you see what is going on.

**Comment by zOOge** [comment]
Hi again, I got it to work after some reading up on ruby and modifying :)
I suppose your scripts were somewhat customized for Nordstrom.
Now it works great, thanks for a nice contrib, saved some work with writing api-scripts :)

**Comment by kodywilson** [comment]
Awesome, glad you got it working!
